import type { Metadata } from "next";
import "./globals.css";
import Foooter from "./_components/Foooter";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth">
      <body className={`antialiased dark:bg-[#080c14] transition-colors duration-300 ease-linear`}>
        {children}
        <Foooter />
      </body>
    </html>
  );
}
